---
image:
  repository: peterevans/nominatim-k8s
  tag: latest
replicas: 1
nominatim:
  ## Array of extra env variables
  ## nominatim:
  ##   extraEnvVars:
  ##     - name: VAR
  ##       value: VALUE
  mode: 'CREATE'
  extraEnvVars:
    NOMINATIM_PBF_URL: ''
    NOMINATIM_DATA_LABEL: ''
    NOMINATIM_SA_KEY_PATH: ''
    NOMINATIM_PROJECT_ID: ''
    NOMINATIM_GS_BUCKET: ''
    NOMINATIM_PG_THREADS: ''
    NOMINATIM_POSTGRESQL_DATA_PATH: ''
  config:
    local: []
postgres:
  version: '9.5'
  postgis: '2.2'
ingress:
  serviceType: ClusterIP
  enabled: false
  annotations: {}
  hosts: []
  tls: []
volumes:
  nominatim-secret-volume:
    secretname: nominatim-storage-secret
    type: secret
  local-data:
    path: /data
    hostpath_type: DirectoryOrCreate
    type: hostPath
  nominatim-local-php:
    type: configMap
